[project]
name = "automatic-3d-pipe-adapter"
version = "0.1.0"
description = "Gnerate 3d model vacume clear adaptrer"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "stl>=0.0.3",
]
