[project]
name = "automatic-3d-pipe-adapter"
version = "0.1.0"
description = "Gnerate 3d model vacume clear adaptrer"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "numpy-stl>=3.2.0",
    "stl>=0.0.3",
    "trimesh>=4.8.3",
]
